// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtslnyq0q4SQoaY2CLk6M4gxptlshlhfU',
    appId: '1:372361215188:web:2f1e65ce013cb7cadf0f41',
    messagingSenderId: '372361215188',
    projectId: 'myfirstapp-a64cf',
    authDomain: 'myfirstapp-a64cf.firebaseapp.com',
    storageBucket: 'myfirstapp-a64cf.appspot.com',
    measurementId: 'G-BZF8ZV1NMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD502cbiPgOets5iUiwHEOU-QyAT_zSJsI',
    appId: '1:372361215188:android:f05409987d1779a6df0f41',
    messagingSenderId: '372361215188',
    projectId: 'myfirstapp-a64cf',
    storageBucket: 'myfirstapp-a64cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ1j3rjkTDdihqoHBVfsvj8910vOIyEdY',
    appId: '1:372361215188:ios:09aca1656c2420d7df0f41',
    messagingSenderId: '372361215188',
    projectId: 'myfirstapp-a64cf',
    storageBucket: 'myfirstapp-a64cf.appspot.com',
    iosClientId: '372361215188-6mn9kegb9vb4sgceuku7pm646i98q9le.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ1j3rjkTDdihqoHBVfsvj8910vOIyEdY',
    appId: '1:372361215188:ios:5e6ff6888d86c290df0f41',
    messagingSenderId: '372361215188',
    projectId: 'myfirstapp-a64cf',
    storageBucket: 'myfirstapp-a64cf.appspot.com',
    iosClientId: '372361215188-5d3h74nqftos9mjpu9v0142u0dq9b9tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication6.RunnerTests',
  );
}
